version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install aws-cdk-lib
  pre_build:
    commands:
      - echo "Synth started on `date`"
  build:
    commands:
      - echo "Synthesizing CDK app..."
      - cdk synth
artifacts:
  base-directory: cdk.out
  files:
    - '**/*'
